name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ARM64

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag megaflops/test
